#!/usr/bin/env python3
"""
Enhanced Job Application Generator
Generates tailored resumes, cover letters, and outreach messages based on job descriptions.
"""

import json
import re
from datetime import datetime
from pathlib import Path
from typing import Dict, List, Tuple, Optional
import argparse

from modules.jd_parser import JobDescriptionParser
from modules.resume_generator import ResumeGenerator
from modules.cover_letter_generator import CoverLetterGenerator
from modules.message_generator import MessageGenerator
from modules.country_config import CountryConfig

class JobApplicationGenerator:
    def __init__(self):
        self.jd_parser = JobDescriptionParser()
        self.resume_generator = ResumeGenerator()
        self.cover_letter_generator = CoverLetterGenerator()
        self.message_generator = MessageGenerator()
        self.country_config = CountryConfig()
        
    def generate_application_package(self, job_description: str, country: str, company_name: str = None) -> str:
        """
        Main workflow: Generate complete application package
        
        Args:
            job_description: Full job description text
            country: Target country (netherlands, finland, ireland, sweden, denmark, portugal)
            company_name: Company name (extracted from JD if not provided)
            
        Returns:
            Path to generated markdown file
        """
        print(f"🎯 Generating application package for {country.title()}...")
        
        # Step 1: Parse job description
        print("📋 Parsing job description...")
        jd_data = self.jd_parser.parse(job_description)
        
        if not company_name:
            company_name = jd_data.get('company', 'UnknownCompany')
        
        # Step 2: Generate resume based on JD requirements
        print("📄 Generating tailored resume...")
        resume_content, resume_changes = self.resume_generator.generate(jd_data, country)
        
        # Step 3: Generate cover letter
        print("📝 Generating cover letter...")
        cover_letter = self.cover_letter_generator.generate(jd_data, country, company_name)
        
        # Step 4: Generate LinkedIn and email messages
        print("💬 Generating outreach messages...")
        linkedin_msg = self.message_generator.generate_linkedin_message(jd_data, country)
        email_msg = self.message_generator.generate_email_message(jd_data, country, company_name)
        
        # Step 5: Compile into single markdown file
        print("📦 Compiling application package...")
        output_path = self._create_output_file(
            company_name, country, resume_content, cover_letter, 
            linkedin_msg, email_msg, resume_changes, jd_data
        )
        
        print(f"✅ Application package generated: {output_path}")
        return output_path
    
    def _create_output_file(self, company_name: str, country: str, 
                           resume: str, cover_letter: str, linkedin_msg: str, 
                           email_msg: str, changes: List[str], jd_data: Dict) -> str:
        """Create the final markdown output file"""
        
        timestamp = datetime.now().strftime("%Y-%m-%d")
        filename = f"{company_name}_{country}_{timestamp}.md"
        output_path = Path("output") / filename
        
        # Calculate ATS match score
        ats_score = jd_data.get('ats_match_score', 0)
        
        content = f"""# {company_name} - {jd_data.get('role_title', 'Product Manager')} Application Package

**Generated:** {datetime.now().strftime("%B %d, %Y at %I:%M %p")}  
**Country:** {country.title()}  
**ATS Match Score:** {ats_score}% {'✅' if ats_score >= 80 else '⚠️'}

---

## Resume

{resume}

---

## Cover Letter

{cover_letter}

---

## LinkedIn Message

**Length:** {len(linkedin_msg)} characters {'✅' if len(linkedin_msg) <= 400 else '⚠️'}

{linkedin_msg}

---

## Email Template

**Subject:** {email_msg['subject']}

{email_msg['body']}

---

## Changes Made

{self._format_changes(changes)}

---

## Skills Analysis

**Matched Skills:** {', '.join(jd_data.get('matched_skills', []))}

**Missing Skills:** {', '.join(jd_data.get('missing_skills', []))}

**Mapped Skills:** {', '.join(jd_data.get('mapped_skills', []))}

---

*Generated by Enhanced Job Application Generator*
"""
        
        with open(output_path, 'w', encoding='utf-8') as f:
            f.write(content)
            
        return str(output_path)
    
    def _format_changes(self, changes: List[str]) -> str:
        """Format the changes list for markdown output"""
        if not changes:
            return "No specific changes made to base resume."
        
        formatted = []
        for i, change in enumerate(changes, 1):
            formatted.append(f"{i}. {change}")
        
        return "\n".join(formatted)

def main():
    """Interactive command line interface"""
    print("🚀 Enhanced Job Application Generator")
    print("=" * 50)
    
    generator = JobApplicationGenerator()
    
    # Get job description
    print("\n📋 Please paste the job description below (press Enter twice when done):")
    job_description_lines = []
    empty_lines = 0
    
    while empty_lines < 2:
        line = input()
        if line.strip() == "":
            empty_lines += 1
        else:
            empty_lines = 0
        job_description_lines.append(line)
    
    job_description = "\n".join(job_description_lines).strip()
    
    if not job_description:
        print("❌ Error: No job description provided.")
        return
    
    # Get country
    print("\n🌍 Select target country:")
    countries = ["netherlands", "finland", "ireland", "sweden", "denmark", "portugal"]
    for i, country in enumerate(countries, 1):
        print(f"  {i}. {country.title()}")
    
    while True:
        try:
            choice = int(input("\nEnter choice (1-6): "))
            if 1 <= choice <= 6:
                selected_country = countries[choice - 1]
                break
            else:
                print("Please enter a number between 1 and 6.")
        except ValueError:
            print("Please enter a valid number.")
    
    # Optional: Get company name
    company_name = input(f"\n🏢 Company name (optional, will extract from JD): ").strip()
    
    # Generate application package
    try:
        output_path = generator.generate_application_package(
            job_description, selected_country, company_name or None
        )
        
        print(f"\n🎉 Success! Application package saved to: {output_path}")
        print(f"\nYou can now copy-paste this content into EnhanceCV or your preferred format.")
        
    except Exception as e:
        print(f"\n❌ Error generating application package: {str(e)}")

if __name__ == "__main__":
    main()